DROP TABLE IF EXISTS score_art_MD02//
DROP TABLE IF EXISTS avg_MD02//
DROP TABLE IF EXISTS sd_MD02//
DROP TABLE IF EXISTS cor_MD02//
DROP TABLE IF EXISTS name_MD02//
DROP TABLE IF EXISTS table_MD02//

DROP TABLE IF EXISTS score_art_MD03//
DROP TABLE IF EXISTS avg_MD03//
DROP TABLE IF EXISTS sd_MD03//
DROP TABLE IF EXISTS cor_MD03//
DROP TABLE IF EXISTS name_MD03//
DROP TABLE IF EXISTS table_MD03//


